language: c++
compiler:
  - gcc
os: linux
dist: bionic
addons:
  apt:
    packages:
      - libuv1-dev
      - libboost-all-dev
      - libssl-dev
      - rapidjson-dev
      - autoconf
      - openjdk-8-jdk-headless
      - maven
      - doxygen
      - texlive-font-utils
      - python-six

before_install:
  - pip install --user cpp-coveralls

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
script: bash ./.travis/travis-build.sh

after_success:
  - coveralls -n --exclude '/usr/include' --exclude '/usr/local/include' --exclude-pattern '.*/test/.*' --build-root 'agent-ovs' --root 'agent-ovs' --gcov-options '\-lp'

